version: "3.8"

services:
  backend:
    image: bhaskar9999/stock-app-backend:version1
    container_name: stock-app-backend

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      kafka:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - stock-network

  frontend:
    image: bhaskar9999/stock-frontend:latest
    container_name: stock-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - stock-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    hostname: kafka

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      # KRaft Mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:29093,EXTERNAL://:29092

      # Advertised Listeners
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://YOUR_EC2_PUBLIC_IP:29092

      # Protocol Mapping
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Cluster Settings
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # Single Broker Settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Auto Topic Creation
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

    restart: unless-stopped

    networks:
      - stock-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui

    ports:
      - "8080:8080"

    depends_on:
      kafka:
        condition: service_healthy

    environment:
      KAFKA_CLUSTERS_0_NAME: production
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_READONLY: "false"

    restart: unless-stopped

    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge